Core upgrade 7.4.1
Talend/tesb-rt-se pull request #226
Opened 2020-11-04 11:17 UTC by xldai

2020-11-05 09:32 UTC, jgreffe requested changes
Do we really need all the JARs inside `talend-esb/src/main/distribution/container/lib/` ? They should already part of the decompressed karaf distribution?

2020-11-05 09:32 UTC, jgreffe commented on talend-esb/pom.xml
>                                  <descriptor>file:${basedir}/target/dependencies/standard-${karaf.version}-features.xml</descriptor>
Can't we use direct `mvn:org.apache.karaf.features/standard/${karaf.version}/xml/features` here?

2020-11-05 09:32 UTC, jgreffe commented on talend-esb/pom.xml
>                                  <descriptor>file:${basedir}/target/dependencies/spring-legacy-${karaf.version}-features.xml</descriptor>
Same here, `mvn:org.apache.karaf.features/spring-legacy/${karaf.version/xml/features` ?

2020-11-05 09:32 UTC, jgreffe commented on talend-esb/pom.xml
>                                  <artifactItem>
We shouldn't need any `<artifactItem>` dependency anymore as they should all come from above features XML?
Only remaining `<artifactItem>` should be for `org.talend.esb` groupId ?

2020-11-05 09:32 UTC, jgreffe commented on talend-esb/src/main/bin/client
> +    CLASSPATH="${KARAF_HOME}/system/org/apache/karaf/org.apache.karaf.client/4.2.10/org.apache.karaf.client-4.2.10.jar"
Maybe we can set these executable with placeholders, and filtered using maven resolution of properties, instead of having to manually replace all versions?

2020-11-05 09:32 UTC, jgreffe commented on talend-esb/src/main/descriptors/assembly.xml
> +        <!-- workaround for Decanter features descriptor -->
Features should already be in container/system with previous

```
<fileSet>
            <directory>target/features-repo</directory>
            <outputDirectory>./container/system</outputDirectory>
...
</fileSet>
```

, so we don't need these explicit features XML copy?

2020-11-06 01:25 UTC, xldai commented on talend-esb/pom.xml
>                                  <descriptor>file:${basedir}/target/dependencies/standard-${karaf.version}-features.xml</descriptor>
+1

2020-11-06 01:25 UTC, xldai commented on talend-esb/pom.xml
>                                  <descriptor>file:${basedir}/target/dependencies/spring-legacy-${karaf.version}-features.xml</descriptor>
+1

2020-11-06 01:40 UTC, xldai commented on talend-esb/pom.xml
>                                  <artifactItem>
For features XML yes will try. 
For bundles/jars still have to keep the <artifactItem> otherwize build will failed during assembling.

2020-11-06 02:05 UTC, xldai commented
> 
> 
> Do we really need all the JARs inside `talend-esb/src/main/distribution/container/lib/` ? They should already part of the decompressed karaf distribution?

yes, we still need to add some dependency libs from CXF into the endorsed/jdk9plus to solve the class loading problems.
also org.apache.servicemix.specs.jaxb-api-2.3-2.3_1-tesb1.jar is patched by Andreas for another issue.

2020-11-06 02:13 UTC, xldai commented on talend-esb/src/main/bin/client
> +    CLASSPATH="${KARAF_HOME}/system/org/apache/karaf/org.apache.karaf.client/4.2.10/org.apache.karaf.client-4.2.10.jar"
Good finding!
now we don't need to patch the client/client.bat anymore, we use the original ones from karaf. will remove the client/client.bat.

2020-11-06 02:25 UTC, xldai commented on talend-esb/src/main/descriptors/assembly.xml
> +        <!-- workaround for Decanter features descriptor -->
checking

2020-11-06 02:30 UTC, xldai commented on talend-esb/src/main/descriptors/assembly.xml
> +        <!-- workaround for Decanter features descriptor -->
Have to keep these.
e.g in the target/features-repo only have apache-karaf-decanter-2.5.0.tesb1-features.xml, it will be renamed to apache-karaf-decanter-2.5.0-features.xml using this fileSet.

2020-11-06 08:12 UTC, jgreffe commented on talend-esb/pom.xml
>                                  <artifactItem>
But bundles/JARs have already been resolved in feature-repo when resolving features XML right?

2020-11-06 08:13 UTC, jgreffe commented on talend-esb/src/main/bin/client
> +    CLASSPATH="${KARAF_HOME}/system/org/apache/karaf/org.apache.karaf.client/4.2.10/org.apache.karaf.client-4.2.10.jar"
Above comment is also for trun/trun.bat and all executables

2020-11-06 08:14 UTC, jgreffe commented on talend-esb/src/main/descriptors/assembly.xml
> +        <!-- workaround for Decanter features descriptor -->
I think we should keep apache-karaf-decanter-2.5.0.tesb1-features.xml without renaming?

2020-11-06 08:15 UTC, jgreffe commented
> > Do we really need all the JARs inside `talend-esb/src/main/distribution/container/lib/` ? They should already part of the decompressed karaf distribution?
> 
> yes, we still need to add some dependency libs from CXF into the endorsed/jdk9plus to solve the class loading problems.
> also org.apache.servicemix.specs.jaxb-api-2.3-2.3_1-tesb1.jar is patched by Andreas for another issue.

I thought we based custom using `.` ? => org.apache.servicemix.specs.jaxb-api-2.3-2.3_1.tesb1.jar

2020-11-09 08:53 UTC, jgreffe requested changes

2020-11-09 08:53 UTC, jgreffe commented on talend-esb/pom.xml
>                                      <groupId>org.apache.karaf.features</groupId>
Do we stil need this artifactItem as it's been processed already in `features-add-to-repository` ?

2020-11-09 08:53 UTC, jgreffe commented on talend-esb/pom.xml
>                                      <artifactId>pax-logging-log4j2</artifactId>
Same here

2020-11-09 08:54 UTC, jgreffe commented
And also comments from previous reviews.

2020-11-10 06:19 UTC, xldai commented on talend-esb/pom.xml
>                                      <groupId>org.apache.karaf.features</groupId>
I checked, and yes it's still needed otherwise these patched feature xml files couldn't be found in "target/dependencies" during assembling (in assembly.xml).
we may improve the assembly.xml in the future time if you don't mind.

2020-11-16 15:29 UTC, jgreffe approved these changes
lgtm 👌

2020-11-23 10:23 UTC, merged