chore(TESB-30682) override jackson databind version from activemq-osgi
Talend/tesb-rt-se pull request #248
Opened 2021-02-22 03:19 UTC by xldai

2021-02-22 07:47 UTC, coheigea approved these changes
Are you also going to update Jackson on the other repos?

2021-02-23 10:35 UTC, xldai commented
@coheigea  here is another PR on tesb-eventlogging https://github.com/Talend/tesb-eventlogging/pull/71

2021-02-23 11:11 UTC, coheigea commented
@xldai Thanks - and is there a separate JIRA to update Jackson in tesb-registry,tesb-authz etc?

2021-02-24 03:51 UTC, xldai commented
@coheigea , I searched in the tesb-registry, tesb-authorization, tesb-provisioning but they don't have activemq-osgi as dependency.

2021-02-24 06:51 UTC, coheigea commented
@xldai No sorry, I meant the core jackson version. This PR updates it to 2.11.x, whereas the other repos are still on 2.10.x.

2021-02-24 08:20 UTC, jgreffe requested changes

2021-02-24 08:20 UTC, jgreffe commented on pom.xml
> +        <jackson.version>2.11.4</jackson.version>
Adding in this pom.xml proper versions is enough, and don't require individual pom.xml updates.
And also with this, we don't introduce dependencies on jackson-databind which are not required (for example in `camel-jmx-service`)

```
<dependencyManagement>
...
<dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
...
</dependencyManagement>

2021-02-24 08:30 UTC, xldai commented
> 
> 
> @xldai No sorry, I meant the core jackson version. This PR updates it to 2.11.x, whereas the other repos are still on 2.10.x.

@coheigea Other changes should be done in scope of this Jira https://jira.talendforge.org/browse/TESB-31889

2021-02-24 08:38 UTC, xldai commented on pom.xml
> +        <jackson.version>2.11.4</jackson.version>
Are you sure Julien? because we add <exclusion> for jackson-databind from activemq-osgi in the parent example pom. and introduce jackson-databind dependency only for the projects which has activemq-osgi dependency inside, not every pom.xml. so that make sure "mvn java:run" will succeed without class loading problem.

2021-03-01 07:48 UTC, xldai commented
Okay, I removed the jackson-databind dependencies in individual examples.
review please? @jgreffe

2021-03-05 08:17 UTC, jgreffe approved these changes

2021-03-05 08:28 UTC, merged