TPRUN-2553 SAPJCO3 multiple endpoint support.
Talend/tesb-rt-se pull request #333
Opened 2021-11-30 19:49 UTC by andreasmattes

2022-01-20 14:26 UTC, jgreffe requested changes

2022-01-20 14:26 UTC, jgreffe commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +        for (Map.Entry<Object, Object> e : properties.entrySet()) {
Potential NPE

2022-01-20 14:26 UTC, jgreffe commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +        for (String ep : endpointNames) {
Potential NPE

2022-01-20 14:26 UTC, jgreffe commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +            endpointNames.add(ep);
Potential NPE

2022-01-25 12:28 UTC, andreasmattes commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +        for (Map.Entry<Object, Object> e : properties.entrySet()) {
caught upfront.

2022-01-25 12:28 UTC, andreasmattes commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +        for (String ep : endpointNames) {
caught upfront.

2022-01-25 12:29 UTC, andreasmattes commented on talend-sapjco3-connector/src/main/java/org/talend/sap/connection/SAPJCo3Connector.java
> +            endpointNames.add(ep);
caught upfront

2022-01-25 15:57 UTC, merged