TPRUN-4846 Patch build preparation.
Talend/tesb-rt-se pull request #497
Opened 2022-12-06 19:30 UTC by andreasmattes

2022-12-06 19:40 UTC, f2par0 requested changes

2022-12-06 19:40 UTC, f2par0 commented on sam/derby-starter/pom.xml
> +        <reviwion>${derby-starter.version}</revision>
Typo here

2022-12-06 19:42 UTC, f2par0 commented on pom.xml
> +                <original.version>7.3.1.R2022-09-RT</original.version>
there was no 2022-10 for the 7.3 branch ?

2022-12-06 22:02 UTC, andreasmattes commented on pom.xml
> +                <original.version>7.3.1.R2022-09-RT</original.version>
no, 2022-09 is the latest full build.

2022-12-06 22:03 UTC, andreasmattes commented on sam/derby-starter/pom.xml
> +        <reviwion>${derby-starter.version}</revision>
this has been fixed

2022-12-07 08:28 UTC, f2par0 submitted a review, later dismissed
LGTM

2022-12-07 14:54 UTC, merged